api_platform:
  title: 'Gratefulness API'
  description: 'This is a simple API that is used by the gratefulness.guru frontend in order to obtain and post quotes from and to the backend.'
  version: 0.0.3
  show_webby: false
  enable_re_doc: false
  graphql:
    enabled: true
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/config/api_platform'
