Gratefulness\Entity\Quote:
  collectionOperations:
    get: ~
    post: ~
    get_random:
      method: 'GET'
      path: '/quotes/random/{language}'
      controller: Gratefulness\Controller\GetRandomQuote
      pagination_enabled: false
      swagger_context:
        summary: Helllo Wooolrrdd
        description: Helllo Wooolrrdd
        parameters:
          - in: path
            name: language
            type: string
            enum:
              - en
              - pt
            required: true
  itemOperations:
    get: ~